events {}
http {
  server {
    listen 443 ssl;
    ssl_certificate     /etc/nginx/tls/conjur.crt;
    ssl_certificate_key /etc/nginx/tls/conjur.key;
    location / {
      proxy_pass http://conjur-server:80;
      proxy_set_header Host $host;
    }
  }
}
